### ISSUE TITLE
Problem with assert

### ISSUE THREAD

**Issue by hangxie** [awslabs/aws-cloudformation-template-formatter#23]
There seems to be a problem with `assert`, cfn-format will remove the function, sample:

```
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  TestKey:
    Type: String
    Description: The key
  TestValue:
    Type: String
    Description: The value
Resources:
  TaskRoleArnParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Ref TestKey
      Type: String
      Value: !Ref TestValue
Rules:
  TestKey:
    Assertions:
      - Assert: !Contains
          - - k1
            - k2
            - k3
          - !Ref TestKey
        AssertDescription: key needs to be k1/k2/k3 when value is dummy
    RuleCondition: !Equals
      - Ref: TestValue
      - dummy
```

becomes:
```
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  TestKey:
    Type: String
    Description: The key

  TestValue:
    Type: String
    Description: The value

Resources:
  TaskRoleArnParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Ref TestKey
      Type: String
      Value: !Ref TestValue

Rules:
  TestKey:
    Assertions:
      - Assert:
          - - k1
            - k2
            - k3
          - Ref: TestKey
        AssertDescription: key needs to be k1/k2/k3 when value is dummy
    RuleCondition: !Equals
      - Ref: TestValue
      - dummy
```

Similar things happened to `EachMemberIn`, I didn't try other functions.
